### ISSUE TITLE
Add cuke:hub[env, @tags] rake to RubyGem

### ISSUE THREAD

**Issue by richdownie** [richdownie/cukehub_gem#1]
secret sauce

**Comment by richdownie** [comment]
I'd like to add my custom build rake tasks to the CukeHub Gem
rake cuke:hub[@tag].  This will enable the CukeHub application to schedule builds form CukeHub.com
```require 'bundler'

namespace :cuke do
  desc "cucunber -t <@tags>"
  task :hub, [:tag] do |t, args|
  file = "#{args[:tag]}".gsub(/@/, '')
    Bundler.with_clean_env do
      console_output = ""
      IO.popen("thor set:chrome_ci && cucumber -t #{args[:tag]} -f rerun --out #{file}.txt", 'r+') do |pipe|
        puts console_output = pipe.read
        pipe.close_write
      end
      IO.popen("cucumber #{args[:tag]}.txt --format html --out=#{file}.html --format pretty", 'r+') do |pipe|
        puts "** RE-RUNNING FAILED #{args[:tags]}.txt SCENARIOS **"
        puts console_output = pipe.read
        pipe.close_write
      end
    end
  end
end```

**Comment by richdownie** [comment]
I can't see the rake -T tasks from the gemspec, however when I 

push the gem to rubygems.org
gem install in another directory
**rake -T** does not see the rake task

![gem_bug](https://cloud.githubusercontent.com/assets/3307/22627497/3489f81a-eb92-11e6-8e98-57a71cfb9b4d.gif)

**Comment by richdownie** [comment]
This is hard

**Comment by jwhitmire** [comment]
Just being in the directory with the gem, you aren't in the context of a rails app (which sets up all the hooks to know where to find rake tasks).  If you have that gem loaded in another rails app, you should see them in the list.  If you don't then there is likely another bit of plumbing that needs to be hooked up to make that work.

**Comment by richdownie** [comment]
Actually, CukeHub is targeting Integration Automation Engineers and Automation Cucumber (+ selenium || watir) Test Repositories that live outside a Rails App.  Having it work in Rails too is a bonus.
